CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(30) NOT NULL
);

CREATE TABLE buses(
id INTEGER PRIMARY KEY AUTOINCREMENT,
bus_number VARCHAR(50) UNIQUE NOT NULL,
driver_name VARCHAR(100) NOT NULL,
route_name VARCHAR(100) NOT NULL,
total_seats INTEGER NOT NULL,
status VARCHAR(20) NOT NULL
);

CREATE TABLE students(
id INTEGER PRIMARY KEY AUTOINCREMENT,
student_name VARCHAR(100) NOT NULL,
admission_number VARCHAR(50) UNIQUE NOT NULL,
class_name VARCHAR(50) NOT NULL,
pickup_location VARCHAR(150) NOT NULL,
bus_id INTEGER NOT NULL,
FOREIGN KEY(bus_id) REFERENCES buses(id)
);

CREATE TABLE attendance(
id INTEGER PRIMARY KEY AUTOINCREMENT,
student_id INTEGER NOT NULL,
bus_id INTEGER NOT NULL,
travel_date DATE NOT NULL,
pickup_status VARCHAR(30) NOT NULL,
drop_status VARCHAR(30) NOT NULL,
FOREIGN KEY(student_id) REFERENCES students(id),
FOREIGN KEY(bus_id) REFERENCES buses(id),
UNIQUE(student_id, travel_date)
);
